In [1]:
#Importing the Libraries
import numpy as np 
import pandas as pd
import warnings
warnings.simplefilter("ignore")
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
plt.style.use('ggplot')
%matplotlib inline

In [2]:
#Importing the Dataset
df=pd.read_csv('bank_marketing_dataset.csv')

In [3]:
df.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct      79.0         1   -1.0         0  unknown  no  
1  cellular   11   may     220.0         1  339.0         4  failure  no  
2  cellular   16   apr     185.0         1  330.0         1  failure  no  
3   unknown    3   jun     199.0         4   -1.0         0  unknown  no  
4   unknown    5   may     226.0         1   -1.0         0  unknown  no

In [4]:
df.tail()

age            job  marital  education default  balance housing loan  \
4516   33       services  married  secondary      no     -333     yes   no   
4517   57  self-employed  married   tertiary     yes    -3313     yes  yes   
4518   57     technician  married  secondary      no      295      no   no   
4519   28    blue-collar  married  secondary      no     1137      no   no   
4520   44   entrepreneur   single   tertiary      no     1136     yes  yes   

       contact  day month  duration  campaign  pdays  previous poutcome   y  
4516  cellular   30   jul     329.0         5   -1.0         0  unknown  no  
4517   unknown    9   may     153.0         1   -1.0         0  unknown  no  
4518  cellular   19   aug     151.0        11   -1.0         0  unknown  no  
4519  cellular    6   feb     129.0         4  211.0         3    other  no  
4520  cellular    3   apr     345.0         2  249.0         7    other  no

In [7]:
#checking for missing values
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4521 entries, 0 to 4520
Data columns (total 17 columns):
age          4521 non-null int64
job          4521 non-null object
marital      4521 non-null object
education    4521 non-null object
default      4521 non-null object
balance      4521 non-null int64
housing      4521 non-null object
loan         4521 non-null object
contact      4521 non-null object
day          4521 non-null int64
month        4521 non-null object
duration     4521 non-null float64
campaign     4521 non-null int64
pdays        4521 non-null float64
previous     4521 non-null int64
poutcome     4521 non-null object
y            4521 non-null object
dtypes: float64(2), int64(5), object(10)
memory usage: 600.5+ KB


In [9]:
#Description of Datase
df.describe()

age       balance          day     duration     campaign  \
count  4521.000000   4521.000000  4521.000000  4521.000000  4521.000000   
mean     41.170095   1422.657819    15.915284   263.961292     2.793630   
std      10.576211   3009.638142     8.247667   259.856633     3.109807   
min      19.000000  -3313.000000     1.000000     4.000000     1.000000   
25%      33.000000     69.000000     9.000000   104.000000     1.000000   
50%      39.000000    444.000000    16.000000   185.000000     2.000000   
75%      49.000000   1480.000000    21.000000   329.000000     3.000000   
max      87.000000  71188.000000    31.000000  3025.000000    50.000000   

             pdays     previous  
count  4521.000000  4521.000000  
mean     39.766645     0.542579  
std     100.121124     1.693562  
min      -1.000000     0.000000  
25%      -1.000000     0.000000  
50%      -1.000000     0.000000  
75%      -1.000000     0.000000  
max     871.000000    25.000000

In [12]:
X=df.drop('y',axis=1) #Predictors
y=df['y'] #Response
X.head()

age          job  marital  education default  balance housing loan  \
0   30   unemployed  married    primary      no     1787      no   no   
1   33     services  married  secondary      no     4789     yes  yes   
2   35   management   single   tertiary      no     1350     yes   no   
3   30   management  married   tertiary      no     1476     yes  yes   
4   59  blue-collar  married  secondary      no        0     yes   no   

    contact  day month  duration  campaign  pdays  previous poutcome  
0  cellular   19   oct      79.0         1   -1.0         0  unknown  
1  cellular   11   may     220.0         1  339.0         4  failure  
2  cellular   16   apr     185.0         1  330.0         1  failure  
3   unknown    3   jun     199.0         4   -1.0         0  unknown  
4   unknown    5   may     226.0         1   -1.0         0  unknown

In [13]:
y

0        no
1        no
2        no
3        no
4        no
5        no
6        no
7        no
8        no
9        no
10       no
11       no
12       no
13      yes
14       no
15       no
16       no
17       no
18       no
19       no
20       no
21       no
22       no
23       no
24       no
25       no
26       no
27       no
28       no
29       no
       ... 
4491     no
4492     no
4493     no
4494    yes
4495     no
4496     no
4497     no
4498     no
4499     no
4500     no
4501     no
4502     no
4503    yes
4504    yes
4505    yes
4506     no
4507     no
4508     no
4509     no
4510     no
4511    yes
4512     no
4513     no
4514     no
4515     no
4516     no
4517     no
4518     no
4519     no
4520     no
Name: y, Length: 4521, dtype: object

In [14]:
#Encoding categorical data:
from sklearn.preprocessing import LabelEncoder
Encoder_X = LabelEncoder() 
for col in X.columns:
    X[col] = Encoder_X.fit_transform(X[col])
Encoder_y=LabelEncoder()
y = Encoder_y.fit_transform(y)

In [15]:
X.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   11   10        1          0        0     1475        0     0        0   
1   14    7        1          1        0     2030        1     1        0   
2   16    4        2          2        0     1303        1     0        0   
3   11    4        1          2        0     1352        1     1        2   
4   40    1        1          1        0      274        1     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  
0   18     10        75         0      0         0         3  
1   10      8       216         0    228         4         0  
2   15      0       181         0    219         1         0  
3    2      6       195         3      0         0         3  
4    4      8       222         0      0         0         3

In [16]:
#Getting dummy variables:
X=pd.get_dummies(X,columns=X.columns,drop_first=True)
X.head()

age_1  age_2  age_3  age_4  age_5  age_6  age_7  age_8  age_9  age_10  \
0      0      0      0      0      0      0      0      0      0       0   
1      0      0      0      0      0      0      0      0      0       0   
2      0      0      0      0      0      0      0      0      0       0   
3      0      0      0      0      0      0      0      0      0       0   
4      0      0      0      0      0      0      0      0      0       0   

      ...      previous_17  previous_18  previous_19  previous_20  \
0     ...                0            0            0            0   
1     ...                0            0            0            0   
2     ...                0            0            0            0   
3     ...                0            0            0            0   
4     ...                0            0            0            0   

   previous_21  previous_22  previous_23  poutcome_1  poutcome_2  poutcome_3  
0            0            0            0           0           0           1  
1            0            0            0           0           0           0  
2            0            0            0           0           0           0  
3            0            0            0           0           0           1  
4            0            0            0           0           0           1  

[5 rows x 3702 columns]

In [17]:
#Splitting the dataset into the Training set and Test set:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [18]:
#Feature Scaling:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [19]:
#principle component analysis:

from sklearn.decomposition import PCA
pca = PCA(n_components=2)

X_train = pca.fit_transform(X_train)
X_test = pca.transform(X_test)

In [20]:
#Creating a func. to evaluate model's performance:

from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

def print_score(classifier,X_train,y_train,X_test,y_test,train=True):
    if train == True:
        print("Training results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_train,classifier.predict(X_train))))
        print('Classification Report:\n{}\n'.format(classification_report(y_train,classifier.predict(X_train))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_train,classifier.predict(X_train))))
        res = cross_val_score(classifier, X_train, y_train, cv=10, n_jobs=-1, scoring='accuracy')
        print('Average Accuracy:\t{0:.4f}\n'.format(res.mean()))
        print('Standard Deviation:\t{0:.4f}'.format(res.std()))
    elif train == False:
        print("Test results:\n")
        print('Accuracy Score: {0:.4f}\n'.format(accuracy_score(y_test,classifier.predict(X_test))))
        print('Classification Report:\n{}\n'.format(classification_report(y_test,classifier.predict(X_test))))
        print('Confusion Matrix:\n{}\n'.format(confusion_matrix(y_test,classifier.predict(X_test))))

In [21]:
                          #logistic regression model
#fitting LR to the training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()

classifier.fit(X_train,y_train)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [22]:
#logistic regression training results
print_score(classifier,X_train,y_train,X_test,y_test,train=True)


Training results:

Accuracy Score: 0.8840

Classification Report:
             precision    recall  f1-score   support

          0       0.89      1.00      0.94      2795
          1       0.54      0.04      0.07       369

avg / total       0.85      0.88      0.84      3164


Confusion Matrix:
[[2784   11]
 [ 356   13]]

Average Accuracy:	0.8843

Standard Deviation:	0.0063


In [23]:
#logistic regression test results
print_score(classifier,X_train,y_train,X_test,y_test,train=False)


Test results:

Accuracy Score: 0.8880

Classification Report:
             precision    recall  f1-score   support

          0       0.89      1.00      0.94      1205
          1       0.00      0.00      0.00       152

avg / total       0.79      0.89      0.84      1357


Confusion Matrix:
[[1205    0]
 [ 152    0]]



In [24]:
                               #Support Vecor (SVC) Classification Model
#Fitting SVC to the Training set:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf',random_state=42)

classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=42, shrinking=True,
  tol=0.001, verbose=False)

In [25]:
#SVC Training Results
print_score(classifier,X_train,y_train,X_test,y_test,train=True)

Training results:

Accuracy Score: 0.8856

Classification Report:
             precision    recall  f1-score   support

          0       0.89      1.00      0.94      2795
          1       0.64      0.04      0.08       369

avg / total       0.86      0.89      0.84      3164


Confusion Matrix:
[[2786    9]
 [ 353   16]]

Average Accuracy:	0.8786

Standard Deviation:	0.0071


In [26]:
#SVC test Results:
print_score(classifier,X_train,y_train,X_test,y_test,train=False)


Test results:

Accuracy Score: 0.8880

Classification Report:
             precision    recall  f1-score   support

          0       0.89      1.00      0.94      1205
          1       0.00      0.00      0.00       152

avg / total       0.79      0.89      0.84      1357


Confusion Matrix:
[[1205    0]
 [ 152    0]]



In [27]:
                  #K Nearest Neighbors (K-NN) Classification Model
#Fitting K-NN to the Training set:
from sklearn.neighbors import KNeighborsClassifier as KNN

classifier = KNN()
classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [28]:
#KNN training results:
print_score(classifier,X_train,y_train,X_test,y_test,train=True)


Training results:

Accuracy Score: 0.8966

Classification Report:
             precision    recall  f1-score   support

          0       0.90      0.99      0.94      2795
          1       0.68      0.21      0.32       369

avg / total       0.88      0.90      0.87      3164


Confusion Matrix:
[[2759   36]
 [ 291   78]]

Average Accuracy:	0.8748

Standard Deviation:	0.0110


In [29]:
#KNN test results:
print_score(classifier,X_train,y_train,X_test,y_test,train=False)


Test results:

Accuracy Score: 0.8850

Classification Report:
             precision    recall  f1-score   support

          0       0.89      0.99      0.94      1205
          1       0.39      0.05      0.08       152

avg / total       0.84      0.89      0.84      1357


Confusion Matrix:
[[1194   11]
 [ 145    7]]



In [30]:
                            #Naive Bayes Classification Model
#Fitting Naive Bayes classifier to the Training set:

from sklearn.naive_bayes import GaussianNB as NB

classifier = NB()
classifier.fit(X_train,y_train)

GaussianNB(priors=None)

In [31]:
#Naive Bayes Training Results:
print_score(classifier,X_train,y_train,X_test,y_test,train=True)


Training results:

Accuracy Score: 0.8571

Classification Report:
             precision    recall  f1-score   support

          0       0.90      0.94      0.92      2795
          1       0.35      0.25      0.29       369

avg / total       0.84      0.86      0.85      3164


Confusion Matrix:
[[2618  177]
 [ 275   94]]

Average Accuracy:	0.8575

Standard Deviation:	0.0188


In [32]:
#Naive Bayes test Results:

print_score(classifier,X_train,y_train,X_test,y_test,train=False)


Test results:

Accuracy Score: 0.8858

Classification Report:
             precision    recall  f1-score   support

          0       0.90      0.98      0.94      1205
          1       0.47      0.17      0.25       152

avg / total       0.86      0.89      0.86      1357


Confusion Matrix:
[[1176   29]
 [ 126   26]]



In [33]:
                             #Decision Tree Classification Model
#Fitting Decision Tree classifier to the Training set:
from sklearn.tree import DecisionTreeClassifier as DT

classifier = DT(criterion='entropy',random_state=42)
classifier.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=42, splitter='best')

In [34]:
#DT training results:
print_score(classifier,X_train,y_train,X_test,y_test,train=True)

Training results:

Accuracy Score: 1.0000

Classification Report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00      2795
          1       1.00      1.00      1.00       369

avg / total       1.00      1.00      1.00      3164


Confusion Matrix:
[[2795    0]
 [   0  369]]

Average Accuracy:	0.8192

Standard Deviation:	0.0055


In [35]:
#DT test results:
print_score(classifier,X_train,y_train,X_test,y_test,train=False)

Test results:

Accuracy Score: 0.8209

Classification Report:
             precision    recall  f1-score   support

          0       0.89      0.91      0.90      1205
          1       0.16      0.14      0.15       152

avg / total       0.81      0.82      0.82      1357


Confusion Matrix:
[[1092  113]
 [ 130   22]]



In [36]:
                           #Random Forest Classification Model
#Fitting Random Forest classifier to the Training set:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 42)
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=50, n_jobs=1, oob_score=False, random_state=42,
            verbose=0, warm_start=False)

In [37]:
#RF trainig results:
print_score(classifier,X_train,y_train,X_test,y_test,train=True)


Training results:

Accuracy Score: 0.9975

Classification Report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00      2795
          1       1.00      0.98      0.99       369

avg / total       1.00      1.00      1.00      3164


Confusion Matrix:
[[2795    0]
 [   8  361]]

Average Accuracy:	0.8710

Standard Deviation:	0.0075


In [38]:
#RF test results:
print_score(classifier,X_train,y_train,X_test,y_test,train=False)


Test results:

Accuracy Score: 0.8843

Classification Report:
             precision    recall  f1-score   support

          0       0.89      0.99      0.94      1205
          1       0.39      0.06      0.10       152

avg / total       0.84      0.88      0.84      1357


Confusion Matrix:
[[1191   14]
 [ 143    9]]

